// Every spoken line in the app. Stable ids: parent voice recordings are keyed by id.
// Rules: Hebrew, male addressing, warm, max ~8 words.
export interface Phrase { text: string; group: string }

const G = {
  station: 'תחנות – הכרזה',
  go: 'תחנות – "עכשיו עושים באמת"',
  label: 'שמות התחנות',
  game: 'הוראות למשחקונים',
  praise: 'שבחים',
  retry: 'ניסיון נוסף (בעדינות)',
  calm: 'הפינה השקטה',
  night: 'לילה ובוקר',
  misc: 'כללי',
} as const;

const raw: [string, string, string][] = [
  // --- announce
  ['st.1.announce', G.station, 'רפאל, בוקר טוב! מתעוררים!'],
  ['st.2.announce', G.station, 'רפאל, עכשיו מצחצחים שיניים!'],
  ['st.3.announce', G.station, 'רפאל, עכשיו מתלבשים!'],
  ['st.4.announce', G.station, 'רפאל, עכשיו אוכלים ארוחת בוקר!'],
  ['st.5.announce', G.station, 'רפאל, עכשיו הולכים לגן!'],
  ['st.6.announce', G.station, 'רפאל, בגן מתנהגים יפה!'],
  ['st.7.announce', G.station, 'רפאל, היום יש חוג כדורגל!'],
  ['st.8.announce', G.station, 'רפאל, היום יש חוג נינג׳ה!'],
  ['st.9.announce', G.station, 'רפאל, עכשיו משחקים בקוביות!'],
  ['st.10.announce', G.station, 'רפאל, עכשיו משחק קופסה!'],
  ['st.11.announce', G.station, 'רפאל, עכשיו ארוחת ערב!'],
  ['st.12.announce', G.station, 'רפאל, עכשיו מתרחצים באמבטיה!'],
  ['st.13.announce', G.station, 'רפאל, הגיע הזמן ללכת לישון!'],
  // --- go do it
  ['st.1.go', G.go, 'קום מהמיטה, מוקה מחכה לך!'],
  ['st.2.go', G.go, 'לך לצחצח שיניים באמת. מוקה מחכה.'],
  ['st.3.go', G.go, 'לך להתלבש באמת. מוקה מחכה.'],
  ['st.4.go', G.go, 'שב לאכול באמת. בתיאבון!'],
  ['st.5.go', G.go, 'בוא נלך לגן באמת. יהיה כיף!'],
  ['st.6.go', G.go, 'בגן תהיה חבר טוב ונחמד.'],
  ['st.7.go', G.go, 'לך לשחק כדורגל באמת. בהצלחה!'],
  ['st.8.go', G.go, 'לך להתאמן באמת. אתה נינג׳ה!'],
  ['st.9.go', G.go, 'בנה משהו מיוחד עם הקוביות.'],
  ['st.10.go', G.go, 'שחק משחק קופסה באמת. תהנה!'],
  ['st.11.go', G.go, 'שב לאכול באמת. בתיאבון!'],
  ['st.12.go', G.go, 'לך להתרחץ באמת. תהנה!'],
  ['st.13.go', G.go, 'לך לישון באמת. לילה טוב.'],
  // --- labels (as on the printed board)
  ['st.1.label', G.label, 'מתעורר בבוקר'],
  ['st.2.label', G.label, 'מצחצח שיניים'],
  ['st.3.label', G.label, 'מתלבש'],
  ['st.4.label', G.label, 'אוכל ארוחת בוקר'],
  ['st.5.label', G.label, 'הולך לגן'],
  ['st.6.label', G.label, 'מתנהג יפה בגן'],
  ['st.7.label', G.label, 'משחק בחוג כדורגל'],
  ['st.8.label', G.label, 'מתאמן בחוג נינג׳ה'],
  ['st.9.label', G.label, 'משחק חופשי בקוביות'],
  ['st.10.label', G.label, 'משחק קופסה'],
  ['st.11.label', G.label, 'אוכל ארוחת ערב'],
  ['st.12.label', G.label, 'מתרחץ באמבטיה'],
  ['st.13.label', G.label, 'הולך לישון'],
  ['next.prefix', G.misc, 'ואחר כך:'],
  ['go.wait', G.misc, 'מוקה מחכה. כשתסיים, ההורה לוחץ על כפה.'],
  ['go.ready', G.misc, 'מוכן? בוא נתחיל!'],
  ['done.cheer', G.misc, 'עשית את זה באמת! וואו!'],
  ['game.intro', G.misc, 'עכשיו משחק קטן, בשבילך!'],
  ['game.end', G.misc, 'סיימנו! איזה כיף היה.'],
  ['map.hello', G.misc, 'בוא נמשיך בדרך!'],
  ['map.allDone', G.misc, 'סיימת את כל היום! כל הכבוד!'],
  // --- praise x5
  ['praise.1', G.praise, 'כל הכבוד רפאל!'],
  ['praise.2', G.praise, 'איזה יופי!'],
  ['praise.3', G.praise, 'וואו, עשית את זה!'],
  ['praise.4', G.praise, 'אתה מדהים!'],
  ['praise.5', G.praise, 'מוקה כל כך גאה בך!'],
  // --- retry x3
  ['retry.1', G.retry, 'כמעט! בוא ננסה שוב'],
  ['retry.2', G.retry, 'קרוב מאוד! עוד פעם'],
  ['retry.3', G.retry, 'לא נורא, ננסה ביחד'],
  // --- games
  ['g.1.how', G.game, 'גע בווילונות כדי לפתוח אותם'],
  ['g.1.stretch', G.game, 'עכשיו גע ברפאל, ותתמתח!'],
  ['g.2.how', G.game, 'העבר את האצבע על הפה ותפוצץ חיידקים'],
  ['g.2.done', G.game, 'השיניים נוצצות!'],
  ['g.3.how', G.game, 'גרור את הבגד אל רפאל'],
  ['g.3.done', G.game, 'רפאל לבוש ומוכן!'],
  ['g.4.how', G.game, 'גרור את האוכל אל הקערה'],
  ['g.4.done', G.game, 'נאם נאם! בתיאבון!'],
  ['g.5.how', G.game, 'גע במסך כדי לצעוד, ולאסוף כוכבים'],
  ['g.6.how', G.game, 'גרור קוביות ובנה מגדל גבוה'],
  ['g.6.star', G.game, 'עכשיו שים כוכב למעלה'],
  ['g.7.how', G.game, 'החלק את הכדור אל השער'],
  ['g.7.goal', G.game, 'גול!'],
  ['g.8.how', G.game, 'גע במסך כדי להתנדנד ולקפוץ'],
  ['g.9.how', G.game, 'גרור צורות ובנה מה שבא לך'],
  ['g.9.finish', G.game, 'כשתסיים, גע בכפתור הירוק'],
  ['g.10.how', G.game, 'גע בקלפים ומצא זוגות'],
  ['g.11.how', G.game, 'גרור את האוכל אל הצלחת'],
  ['g.11.water', G.game, 'ועכשיו כוס מים לשולחן'],
  ['g.12.how', G.game, 'העבר אצבע וקרצף, ותפוצץ בועות'],
  ['g.13.how', G.game, 'גע במנורות כדי לכבות אותן'],
  ['g.13.teddy', G.game, 'עכשיו גרור את הדובי למיטה'],
  ['g.13.moka', G.game, 'מוקה שוכבת לישון'],
  // --- calm corner
  ['calm.offer', G.calm, 'נראה שקשה. רוצה לבוא איתי לפינה השקטה?'],
  ['calm.welcome', G.calm, 'הנה הפינה השקטה של מוקה'],
  ['calm.pick', G.calm, 'מה בא לך לעשות?'],
  ['calm.water.how', G.calm, 'שים אצבע על הכוס, ושתה לאט'],
  ['calm.ball.how', G.calm, 'לחץ והחזק לאט, ואז שחרר'],
  ['calm.pet.how', G.calm, 'ליטוף איטי איטי למוקה'],
  ['calm.pet.slow', G.calm, 'לאט... היא אוהבת לאט'],
  ['calm.breath.how', G.calm, 'נשימה גדולה, ונפח את הבלון'],
  ['calm.breath.in', G.calm, 'שואפים אוויר...'],
  ['calm.breath.out', G.calm, 'ונושפים לאט...'],
  ['calm.breath.hold', G.calm, 'החזק לשאוף, שחרר לנשוף'],
  ['calm.nice', G.calm, 'יפה מאוד. לאט ושקט.'],
  ['calm.feel.ask', G.calm, 'איך אתה מרגיש עכשיו?'],
  ['calm.feel.more', G.calm, 'בוא ננסה עוד משהו שקט'],
  ['calm.feel.green', G.calm, 'איזה כיף! אתה רגוע'],
  ['calm.bridge.water', G.calm, 'עכשיו בוא נשתה כוס מים אמיתית'],
  ['calm.bridge.ball', G.calm, 'עכשיו בוא נלחץ כדור אמיתי'],
  ['calm.bridge.pet', G.calm, 'עכשיו בוא נלטף את מוקה באמת'],
  ['calm.bridge.breath', G.calm, 'עכשיו בוא ננשום נשימה גדולה באמת'],
  ['calm.medal', G.calm, 'קיבלת מדליית רוגע!'],
  ['calm.back', G.calm, 'בוא נחזור למקום שהיינו בו'],
  // --- night / morning
  ['night.1', G.night, 'לילה טוב רפאל. חלומות מתוקים.'],
  ['night.2', G.night, 'מוקה ישנה. גם אתה ישן.'],
  ['morning.1', G.night, 'בוקר טוב רפאל! יום חדש מתחיל!'],
];

export const PHRASES: Record<string, Phrase> = Object.fromEntries(
  raw.map(([id, group, text]) => [id, { text, group }]),
);
export const PHRASE_IDS = raw.map((r) => r[0]);
export const text = (id: string): string => PHRASES[id]?.text ?? id;

export const PRAISE_IDS = ['praise.1', 'praise.2', 'praise.3', 'praise.4', 'praise.5'];
export const RETRY_IDS = ['retry.1', 'retry.2', 'retry.3'];
