import { chromium, devices } from '@playwright/test';
const b = await chromium.launch(); const ctx = await b.newContext({ ...devices['Pixel 7'] }); const p = await ctx.newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message)); p.on('console', (m) => m.type() === 'error' && errs.push(m.text()));
await p.addInitScript(() => { window.__n = 0; const st = AudioBufferSourceNode.prototype.start; AudioBufferSourceNode.prototype.start = function (...a) { window.__n++; return st.apply(this, a); }; });
await p.goto('https://s-cyber8.github.io/day-quest/');
await p.evaluate(() => navigator.serviceWorker.ready.then(() => true)); await p.waitForTimeout(6000);
const cached = await p.evaluate(async () => { const ks = await caches.keys(); let n = 0; for (const k of ks) n += (await (await caches.open(k)).keys()).filter((r) => r.url.endsWith('.mp3')).length; return n; });
await p.reload(); await p.waitForTimeout(1500);
await ctx.setOffline(true);
await p.getByTestId('node-1').click(); await p.waitForTimeout(3500);
console.log({ cachedMp3: cached, speech: await p.evaluate(() => document.body.dataset.speech), sources: await p.evaluate(() => window.__n), errs: errs.filter((e) => !/ERR_INTERNET_DISCONNECTED/.test(e)) });
await b.close();
